version: 2
updates:
  - package-ecosystem: maven
    directory: /
    target-branch: master
    schedule:
      interval: weekly
      day: monday
  - package-ecosystem: github-actions
    directory: /
    target-branch: master
    schedule:
      interval: weekly
      day: monday
